name=swarmpipe-source
connector.class=io.debezium.connector.mysql.MySqlConnector
tasks.max=1

schema.history.internal.kafka.bootstrap.servers=localhost:9092
schema.history.internal.kafka.topic=schemahistory

database.hostname=localhost
database.port=3306
database.user=manikandan
database.password=root
database.server.id=1
database.include.list=swarmpipe_db

topic.prefix=swarmpipe

table.include.list=swarmpipe_db.sites,swarmpipe_db.buildings,swarmpipe_db.assets,swarmpipe_db.sensors,swarmpipe_db.iot_telemetry,swarmpipe_db.events

snapshot.mode=initial
decimal.handling.mode=double

key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
